meta_product_name: "PawFinder"
meta_title: "PawFinder - Find dog-friendly activities near you!"
meta_description: "PawFinder not only connects dog owners together, but gives them all the dog-related info they may need for the best day with their pup! From dog-friendly eating spots to locations of dog-bins, parks, and possible playmates. You can find it all here!"
meta_image: "pawfinder_ogimage.jpg"
